#:schema https://github.com/YunoHost/apps/raw/main/schemas/config_panel.v1.schema.json

version = "1.0"

[main]

services = ["__APP__"]
# or services = ["nginx", "__APP__"] to also reload-or-restart nginx

    [main.customization]
    name.en = "Customization"
    name.fr = "Personalisation"
    optional = false
        ## Note: visible and optional properties are also available for questions

        [main.customization.contact_url]
        ask.en = "Calendar specification file"
        ask.fr = "Fichier de sp√©cifications du calendrier"
        type = "file"
        bind = "__INSTALL_DIR__/open_web_calendar/default_specification.yml"

